### ISSUE TITLE
wait_for_transaction

### ISSUE THREAD

**Issue by Xing-Huang** [yuan-xy/libra-client#7]
There are two reasons to verify whether the major_status of TransactionInfo is more suitable:
1. Can get error information
2. Some transactions are successful without events, such as sending a contract

**Comment by Xing-Huang** [comment]
Seems to understand the reason, thank you for providing such an excellent library

**Comment by Xing-Huang** [comment]
Just tried it, sending a transaction that exceeds all my balance is the same as sending a contract transaction return

**Comment by yuan-xy** [comment]
You are right, check major_status of TransactionInfo is more suitable.
